openapi: 3.1.0
info:
  title: Mongodb assignment api
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /user/login:
    post:
      summary: login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                password:
                  type: string
              example:
                email: 'mortysmith@example.com'
                password: 'mortysmith'
      responses:
        '200':
          description: 'ok'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                id: 1
                name: 'morty smith'
                username: 'morty123'
                email: 'mortysmith@example.com'
        '401':
          description: 'unauthorized'
          content:
            application/json:
              schema:
                type: string
                default: 'wrong credentials'

  /user/{id}:
    get:
      summary: get user details
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: user id
      responses:
        '200':
          description: get user details
          content:
            application/json:
              schema:
                $ref: '#components/schemas/User'

components:
  schemas:
    User:
      properties:
        id:
          type: integer
        name:
          type: string
        username:
          type: string
        email:
          type: string
